name: Mod Scanner Submission
about: Submit your mod scan results to help improve the Mod Scanner tool
labels: ['mod-scanner', 'data-submission']
assignees: ''
body:
  - type: markdown
    attributes:
      value: |
        ## Mod Scanner Submission
        Thank you for helping improve the Mod Scanner!
        
        **Please attach your exported mod scan results JSON file.**
        (Use the "Export Results" button in the Mod Scanner tool, then drag and drop the file here.)
  - type: textarea
    id: extra-context
    attributes:
      label: Extra context (optional)
      description: If you'd like, provide any additional information about your modpack or the scan results.
      placeholder: e.g. Minecraft version, modpack name, or anything unusual you noticed
    validations:
      required: false
